### ISSUE TITLE
[Request] Compiled binary

### ISSUE THREAD

**Issue by Pk13055** [bytedeco/procamtracker#8]
Can you please provide the compiled binary as part of the releases? [The link](https://github.com/bytedeco/procamcalib/releases) mentioned has binaries for `procamcalib` but not `procamtracker`. Thanks in advance! [The link](http://www.ok.sc.e.titech.ac.jp/res/PCS/research/procamtracker/) on your website appears to be broken too. 

(PS - Really appreciate this piece of code! Would love to discuss my use case further _and_ a _potential_ port over to Python, if you're interested)

**Comment by saudet** [comment]
They're available here: https://github.com/bytedeco/procamtracker/releases

**Comment by Pk13055** [comment]
Thanks!
